face, palm and crosstalk tests
matrix-io/matrix-srcjs-apps pull request #2
Opened 2016-11-18 23:54 UTC by heitorgo1

all tests show data on their respectives datashboards

2016-11-23 16:17 UTC, eighteyes commented on gestureTest/config.yaml
> +    y: interger
`integer`

2016-11-23 18:13 UTC, eighteyes commented
Are these tested? I'm trying to run the crosstalkConsumer / Producer and it's failing

2016-11-23 18:58 UTC, eighteyes commented on crosstalkConsumerTest/app.js
> +    if (typeof payload.value === 'number')
this is coming in as { type: 'app-message', payload: { randVal: 29 } }

2016-11-23 19:02 UTC, eighteyes requested changes
please test the crosstalk apps in conjunction before sending a PR. 

```
(crosstalkConsumerTest)err [(crosstalkConsumerTest)]⁊
specificValue not formatted correctly
 specificEmitter { type: 'app-crosstalkConsumerTest-message',
  payload: { randVal: 'h' } }
```

Is the error I get when trying to run both.

2016-11-23 19:02 UTC, eighteyes commented
Also fix conflicts please/

2016-12-06 18:03 UTC, eighteyes commented
@heitorgo1 what's going on here?

2016-12-06 19:00 UTC, heitorgo1 commented
Sorry, haven't been able to solve the conflicts yet, our matrix was unavailable because @di3goleite was using it in presentations for some events around here. Now he's back, and as soon as I get the matrix I'll solve this.

2016-12-07 19:16 UTC, heitorgo1 commented
@eighteyes both crosstalkConsumerTest and crosstalkProducerTest are running without errors now, but I'd like to show you something strange.
Sometimes the emitted message comes in the Consumer with some additional attributes, sometimes it doesn't, here's an example: 

`*******************PAYLOAD********************* { randVal: 76, type: 'app-message' }`
`*******************PAYLOAD********************* { type: 'app-message', payload: { randVal: 76 } }`

The same variable `randVal` sometimes comes wrapped in a `payload` object, and sometimes it doesn't.
I had to deal with these strange situations in the code for it to work as expected.

2016-12-30 17:04 UTC, eighteyes commented
@heitorgo1 closing this PR. please fix conflicts, issues and resolve

2016-12-30 17:04 UTC, closed without merging